- name: Load AWS secrets 
  include_vars: secrets.yml

- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "ubuntu-ec2-instance"
    region: "{{aws_region}}"
    key_name: "{{key_name}}"
    instance_type: "{{instance_type}}"
    security_group: "{{security_group}}"
    network:
      assign_public_ip: true
    image_id: "{{Image_id}}"
    wait : yes
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"